version: 2

jobs:
  build:
    docker:
      - image: circleci/7.4-cli-buster
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install gd
      - restore_cache:
          keys:
            - dependencies-{{ checksum "composer.json" }}
            - dependencies-
      - run:
          name: Install Dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run Tests
          command: composer test
