version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.4-cli-buster
    steps:
      - checkout
      - run: sudo apt update && sudo apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev
      - run: sudo docker-php-ext-configure gd --with-freetype --with-jpeg && docker-php-ext-install -j$(nproc) gd
      - restore_cache:
          keys:
            - dependencies-{{ checksum "composer.json" }}
            - dependencies-
      - run:
          name: Install Dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Run Tests
          command: composer test
